"""del_is_admin

Revision ID: 3c753a92d7e9
Revises: ee2ad8a83fd2
Create Date: 2023-05-03 13:41:57.128945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c753a92d7e9'
down_revision = 'ee2ad8a83fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
